# -*- coding: utf-8 -*-
"""find the length of the longest substring without repeating characters.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvA6F6AenMTBpNPv8CIFs9m_6HZeHz4K
"""

class Solution:
    def longestSubstring(self, s: str) -> str:
        char_map = {}
        start = 0
        max_length = 0
        result = ""

        for end in range(len(s)):
            if s[end] in char_map:
                start = max(start, char_map[s[end]] + 1)

            char_map[s[end]] = end

            if end - start + 1 > max_length:
                max_length = end - start + 1
                result = s[start:end+1]

        return result


# Driver Code
s = input("Enter string: ")
obj = Solution()
print("Longest substring:", obj.longestSubstring(s))